### ISSUE TITLE
你是用cocpods安装的还是直接将文件放在项目中？

### ISSUE THREAD

**Issue by WinnerZhu** [IMCCP/CCPAFNNetworking#2]
你是用cocpods安装的还是直接将文件放在项目中？  我直接将CCPNetworking文件copy到了工程中，但是会有如下报错。烦请帮我看看。  邮箱，343990209@qq.com
Undefined symbols for architecture x86_64:"_OBJC_CLASS_$_CCPNetworking", referenced from:
      objc-class-ref in IntradayGanhuoViewController-D13AA2768E8E5688.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iccpeng** [comment]
没有使用cocpods，报错的原因可能是之前你的项目中导入过 AFN 或者 MB ,再次导入文件的时候可能出现了文件关联错误。
http://blog.csdn.net/hengshujiyi/article/details/21182813/
